version: "2"

services:
  pingdirectory:
    image: pingidentity/pingdirectory:${TAG}
    environment:
      - PING_IDENTITY_DEVOPS_USER=${PING_IDENTITY_DEVOPS_USER}
      - PING_IDENTITY_DEVOPS_KEY=${PING_IDENTITY_DEVOPS_KEY}
      - SERVER_PROFILE_URL=https://github.com/pingidentity/pingidentity-server-profiles.git
      - SERVER_PROFILE_PATH=simple-sync/pingdirectory
  sut:
    build: .
    image: pingidentity/pingdatasync
    environment:
      - PING_IDENTITY_DEVOPS_USER=${PING_IDENTITY_DEVOPS_USER}
<<<<<<< HEAD
      - PING_IDENTITY_DEVOPS_USER=${PING_IDENTITY_DEVOPS_USER}
=======
      - PING_IDENTITY_DEVOPS_KEY=${PING_IDENTITY_DEVOPS_KEY}
>>>>>>> ac8f22c1a12dd4c046abeb3ee0e0c2f44ad00c93
      - SERVER_PROFILE_URL=https://github.com/pingidentity/pingidentity-server-profiles.git
      - SERVER_PROFILE_PATH=simple-sync/pingdatasync
      - VERBOSE=true
    command: start-server /opt/wait-for localhost:389 -t 300 -- /opt/tests/build.test.sh
    depends_on: ["pingdirectory"]
