version: "2"

services:
  pingdirectory:
    image: pingidentity/pingdirectory:${TAG}
    environment:
      - SERVER_PROFILE_URL=https://github.com/pingidentity/pingidentity-server-profiles.git
      - SERVER_PROFILE_PATH=simple-sync/pingdirectory
      - SERVER_PROFILE_PARENT=LICENSE
      - SERVER_PROFILE_LICENSE_URL=https://github.com/pingidentity/pingidentity-server-profiles.git
      - SERVER_PROFILE_LICENSE_PATH=licenses/pingdirectory
  sut:
    build: .
    image: pingidentity/pingdatasync
    environment:
      - SERVER_PROFILE_URL=https://github.com/pingidentity/pingidentity-server-profiles.git
      - SERVER_PROFILE_PATH=simple-sync/pingdatasync
      - SERVER_PROFILE_PARENT=LICENSE
      - SERVER_PROFILE_LICENSE_URL=https://github.com/pingidentity/pingidentity-server-profiles.git
      - SERVER_PROFILE_LICENSE_PATH=licenses/pingdirectory
      - VERBOSE=true
    command: start-server /opt/wait-for localhost:389 -t 300 -- /opt/tests/build.test.sh
    depends_on: ["pingdirectory"]
