version: "3"

services:
  pingdirectory:
    image: pingidentity/pingdirectory:${TAG}
    environment:
      - PING_IDENTITY_DEVOPS_USER=${PING_IDENTITY_DEVOPS_USER}
      - PING_IDENTITY_DEVOPS_KEY=${PING_IDENTITY_DEVOPS_KEY}
      - PING_IDENTITY_ACCEPT_EULA=YES
      - SERVER_PROFILE_URL=https://github.com/pingidentity/pingidentity-server-profiles.git
      - SERVER_PROFILE_PATH=simple-sync/pingdirectory
  sut:
    build: .
    image: pingidentity/pingdatasync:${TAG}
    environment:
      - PING_IDENTITY_DEVOPS_USER=${PING_IDENTITY_DEVOPS_USER}
      - PING_IDENTITY_DEVOPS_KEY=${PING_IDENTITY_DEVOPS_KEY}
      - PING_IDENTITY_ACCEPT_EULA=YES
      - SERVER_PROFILE_URL=https://github.com/pingidentity/pingidentity-server-profiles.git
      - SERVER_PROFILE_PATH=simple-sync/pingdatasync
      - VERBOSE=true
    command: start-server /opt/wait-for localhost:389 -t 300 -- /opt/tests/build.test.sh
    depends_on: ["pingdirectory"]
