version: "2"

services:
  sut:
    build: .
    image: pingidentity/pingdirectory:${TAG}
    environment:
      - SERVER_PROFILE_URL=https://github.com/pingidentity/pingidentity-server-profiles.git
      - SERVER_PROFILE_PATH=getting-started/pingdirectory
      - SERVER_PROFILE_PARENT=LICENSE
      - SERVER_PROFILE_LICENSE_URL=https://github.com/pingidentity/pingidentity-server-profiles.git
      - SERVER_PROFILE_LICENSE_PATH=licenses/pingdirectory
    command: start-server /opt/wait-for localhost:389 -t 300 -- ldapsearch -b "dc=example,dc=com" -s base '(&)' 1.1

    