version: "2"

services:
  sut:
    build: .
    image: pingidentity/pingdatagovernancepap:${TAG}
    environment:
      - PING_IDENTITY_DEVOPS_USER=${PING_IDENTITY_DEVOPS_USER}
      - PING_IDENTITY_DEVOPS_KEY=${PING_IDENTITY_DEVOPS_KEY}
      - VERBOSE=false
    command: start-server /opt/wait-for localhost:${HTTPS_PORT} -t 300 -- /opt/liveness.sh

    