version: "3"

services:
  pingdirectory:
    image: ${REGISTRY}/pingdirectory:8.0.0.1-alpine-az11-${GIT_TAG}
    environment:
      - PING_IDENTITY_DEVOPS_USER=${PING_IDENTITY_DEVOPS_USER}
      - PING_IDENTITY_DEVOPS_KEY=${PING_IDENTITY_DEVOPS_KEY}
      - PING_IDENTITY_ACCEPT_EULA=YES
      - SERVER_PROFILE_URL=https://github.com/pingidentity/pingidentity-server-profiles.git
      - SERVER_PROFILE_PATH=simple-sync/pingdirectory
    ulimits:
      nproc:
        soft: 16384
        hard: 16384
      nofile:
        soft: 65535
        hard: 65535

  sut:
    image: ${REGISTRY}/pingdatasync:8.0.0.1-alpine-az11-${GIT_TAG}
    environment:
      - PING_IDENTITY_DEVOPS_USER=${PING_IDENTITY_DEVOPS_USER}
      - PING_IDENTITY_DEVOPS_KEY=${PING_IDENTITY_DEVOPS_KEY}
      - PING_IDENTITY_ACCEPT_EULA=YES
      - SERVER_PROFILE_URL=https://github.com/pingidentity/pingidentity-server-profiles.git
      - SERVER_PROFILE_PATH=simple-sync/pingdatasync
      - SERVER_PROFILE_BRANCH=gdo-146-manage-profile
    volumes:
      - ./pds-pd.latest.test.sh:/opt/test.sh
    ulimits:
      nproc:
        soft: 16384
        hard: 16384
      nofile:
        soft: 65535
        hard: 65535
    command: start-server /opt/wait-for localhost:389 -t 300 -- /opt/test.sh
    depends_on: ["pingdirectory"]
