version: "2"

services:
  pingdirectory:
    image: ${REGISTRY}/pingdirectory:${PINGDIRECTORY_LATEST}-alpine-az11-${GIT_TAG}
    environment:
      - SERVER_PROFILE_PATH=simple-sync/pingdirectory
      - USER_BASE_DN=o=sync
      - MAX_HEAP_SIZE=768m
    env_file:
      - /tmp/integration_tests.properties
    ulimits:
      nproc:
        soft: 16384
        hard: 16384
      nofile:
        soft: 65535
        hard: 65535
    mem_limit: 1g
    memswap_limit: 1g
    mem_swappiness: 0

  pingdatasync:
    image: ${REGISTRY}/pingdatasync:${PINGDATASYNC_LATEST}-alpine-az11-${GIT_TAG}
    environment:
      - SERVER_PROFILE_PATH=simple-sync/pingdatasync
      - USER_BASE_DN=o=sync
    env_file:
      - /tmp/integration_tests.properties
    ulimits:
      nproc:
        soft: 16384
        hard: 16384
      nofile:
        soft: 65535
        hard: 65535
    mem_limit: 1g
    memswap_limit: 1g
    mem_swappiness: 0
    depends_on: ["pingdirectory"]

  sut:
    image: postman/newman
    entrypoint: ["/usr/bin/env"]
    command: sh -c "/tmp/wait-for pingdirectory:389 -t 900 -- newman run /tmp/collection.json --insecure --ignore-redirects"
    volumes:
      - ./pds-pd.postman_collection.json:/tmp/collection.json
      - ./wait-for:/tmp/wait-for
    depends_on: ["pingdatasync"]