version: "2"

services:
  sut:
    build: .
    image: pingidentity/pingfederate:${TAG}
    environment:
      - PING_IDENTITY_DEVOPS_USER=${PING_IDENTITY_DEVOPS_USER}
      - PING_IDENTITY_DEVOPS_KEY=${PING_IDENTITY_DEVOPS_KEY}
      - PING_IDENTITY_ACCEPT_EULA=YES
      - SERVER_PROFILE_URL=https://github.com/pingidentity/pingidentity-server-profiles.git
      - SERVER_PROFILE_PATH=getting-started/pingfederate
      - PF_ENGINE_PORT=9031
    # the url to wait-for should be on the same port as the container is configured to listen on
    command: start-server /opt/wait-for localhost:9031 -t 300 -- /opt/liveness.sh

    