version: "2"

services:
  sut:
    build: .
    image: pingidentity/pingfederate:${TAG}
    environment:
      - SERVER_PROFILE_URL=https://github.com/pingidentity/pingidentity-server-profiles.git
      - SERVER_PROFILE_PATH=getting-started/pingfederate
    command: start-server /opt/wait-for localhost:9031 -t 300 -- /opt/liveness.sh

    